structure(list(url = "http://statistics.gov.scot/sparql", status_code = 400L, 
    headers = structure(list(server = "nginx", date = "Mon, 02 Mar 2020 15:08:02 GMT", 
        `content-type` = "text/plain; charset=utf-8", `transfer-encoding` = "chunked", 
        connection = "keep-alive", status = "400 Bad Request", 
        `x-frame-options` = "SAMEORIGIN", `x-xss-protection` = "1; mode=block", 
        `x-content-type-options` = "nosniff", `cache-control` = "no-cache", 
        `x-request-id` = "18aab3f5-d089-4236-85fd-8cac52e80921", 
        `x-runtime` = "3.670105"), class = c("insensitive", "list"
    )), all_headers = list(list(status = 400L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Mon, 02 Mar 2020 15:08:02 GMT", 
            `content-type` = "text/plain; charset=utf-8", `transfer-encoding` = "chunked", 
            connection = "keep-alive", status = "400 Bad Request", 
            `x-frame-options` = "SAMEORIGIN", `x-xss-protection` = "1; mode=block", 
            `x-content-type-options` = "nosniff", `cache-control` = "no-cache", 
            `x-request-id` = "18aab3f5-d089-4236-85fd-8cac52e80921", 
            `x-runtime` = "3.670105"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("Response too large"), date = structure(1583161682, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 3e-05, 
    connect = 0.020012, pretransfer = 0.02012, starttransfer = 0.020124, 
    total = 3.731043)), class = "response")
