# Finds lower level geographies

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?geography ?description
WHERE {
  ?data <http://purl.org/linked-data/sdmx/2009/dimension#refArea> ?geographyURI.
  ?geographyURI <http://publishmydata.com/def/ontology/foi/within> <http://statistics.gov.scot/id/statistical-geography/[geography]>.
  ?geographyURI <http://publishmydata.com/def/ontology/foi/memberOf> ?descriptionURI.
  ?descriptionURI rdfs:label ?description.
  ?geographyURI <http://publishmydata.com/def/ontology/foi/code> ?geography.
}
order by ?geography
